server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    reactor.netty.channel: INFO
okta:
  oauth2:
    issuer: https://dev-634061.okta.com/oauth2/default
    client-id: 0oae2q0onBk8GDsve356
    client-secret: 3si8hLYjLgVQGsnnkDa1osiXPBzh3OK2X4JyRl8o

users-url: localhost:8081/users