server:
  port: 8080
logging:
  level:
    reactor:
      netty:
        channel: DEBUG
spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-634061.okta.com/oauth2/default
        registration:
          okta:
            client-id: 0oae2q0onBk8GDsve356
            client-secret: 3si8hLYjLgVQGsnnkDa1osiXPBzh3OK2X4JyRl8o
            scope: openid, email, profile

users-url: localhost:8081/users