server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    reactor.netty.channel: DEBUG
spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-634061.okta.com/oauth2/default
        registration:
          okta:
            client-id: 0oae2q0onBk8GDsve356
            client-secret: 3si8hLYjLgVQGsnnkDa1osiXPBzh3OK2X4JyRl8o
friends-url: localhost:9090/friends